//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 10:00:55 PM EST 
//


package org.osmdroid.wms.v111;

/**
 * 
 */
////@XmlAccessorType(XmlAccessType.FIELD)
/*//@XmlType(name = "", propOrder = {
    "title",
    "onlineResource",
    "logoURL"
})
//@XmlRootElement(name = "Attribution")*/
public class Attribution {

    ////@XmlElement(name = "Title")
    protected String title;
    ////@XmlElement(name = "OnlineResource")
    protected OnlineResource onlineResource;
    ////@XmlElement(name = "LogoURL")
    protected LogoURL logoURL;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the onlineResource property.
     * 
     * @return
     *     possible object is
     *     {@link OnlineResource }
     *     
     */
    public OnlineResource getOnlineResource() {
        return onlineResource;
    }

    /**
     * Sets the value of the onlineResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnlineResource }
     *     
     */
    public void setOnlineResource(OnlineResource value) {
        this.onlineResource = value;
    }

    /**
     * Gets the value of the logoURL property.
     * 
     * @return
     *     possible object is
     *     {@link LogoURL }
     *     
     */
    public LogoURL getLogoURL() {
        return logoURL;
    }

    /**
     * Sets the value of the logoURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogoURL }
     *     
     */
    public void setLogoURL(LogoURL value) {
        this.logoURL = value;
    }

}
