//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 10:00:55 PM EST 
//


package org.osmdroid.wms.v111;

import java.util.ArrayList;
import java.util.List;
/*
//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlAttribute;
//import javax.xml.bind.annotation.XmlElement;
//import javax.xml.bind.annotation.XmlRootElement;
//import javax.xml.bind.annotation.XmlType;
//import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
//import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
//import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
(


////@XmlAccessorType(XmlAccessType.FIELD)
////@XmlType(name = "", propOrder = {
    "name",
    "title",
    "_abstract",
    "keywordList",
    "srs",
    "latLonBoundingBox",
    "boundingBox",
    "dimension",
    "extent",
    "attribution",
    "authorityURL",
    "identifier",
    "metadataURL",
    "dataURL",
    "featureListURL",
    "style",
    "scaleHint",
    "layer"
})
////@XmlRootElement(name = "Layer")
*/
public class Layer {

    ////@XmlAttribute(name = "queryable")
    ////@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String queryable;
    ////@XmlAttribute(name = "cascaded")
    ////@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cascaded;
    ////@XmlAttribute(name = "opaque")
    ////@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String opaque;
    ////@XmlAttribute(name = "noSubsets")
    ////@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String noSubsets;
    ////@XmlAttribute(name = "fixedWidth")
    ////@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fixedWidth;
    ////@XmlAttribute(name = "fixedHeight")
    ////@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fixedHeight;
    ////@XmlElement(name = "Name")
    protected String name;
    ////@XmlElement(name = "Title", required = true)
    protected String title;
    ////@XmlElement(name = "Abstract")
    protected String _abstract;
    ////@XmlElement(name = "KeywordList")
    protected KeywordList keywordList;
    ////@XmlElement(name = "SRS")
    protected List<SRS> srs;
    ////@XmlElement(name = "LatLonBoundingBox")
    protected LatLonBoundingBox latLonBoundingBox;
    ////@XmlElement(name = "BoundingBox")
    protected List<BoundingBox> boundingBox;
    ////@XmlElement(name = "Dimension")
    protected List<Dimension> dimension;
    ////@XmlElement(name = "Extent")
    protected List<Extent> extent;
    ////@XmlElement(name = "Attribution")
    protected Attribution attribution;
    ////@XmlElement(name = "AuthorityURL")
    protected List<AuthorityURL> authorityURL;
    ////@XmlElement(name = "Identifier")
    protected List<Identifier> identifier;
    ////@XmlElement(name = "MetadataURL")
    protected List<MetadataURL> metadataURL;
    ////@XmlElement(name = "DataURL")
    protected List<DataURL> dataURL;
    ////@XmlElement(name = "FeatureListURL")
    protected List<FeatureListURL> featureListURL;
    ////@XmlElement(name = "Style")
    protected List<Style> style;
    ////@XmlElement(name = "ScaleHint")
    protected ScaleHint scaleHint;
    ////@XmlElement(name = "Layer")
    protected List<Layer> layer;

    /**
     * Gets the value of the queryable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryable() {
        if (queryable == null) {
            return "0";
        } else {
            return queryable;
        }
    }

    /**
     * Sets the value of the queryable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryable(String value) {
        this.queryable = value;
    }

    /**
     * Gets the value of the cascaded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCascaded() {
        return cascaded;
    }

    /**
     * Sets the value of the cascaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCascaded(String value) {
        this.cascaded = value;
    }

    /**
     * Gets the value of the opaque property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpaque() {
        if (opaque == null) {
            return "0";
        } else {
            return opaque;
        }
    }

    /**
     * Sets the value of the opaque property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpaque(String value) {
        this.opaque = value;
    }

    /**
     * Gets the value of the noSubsets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoSubsets() {
        if (noSubsets == null) {
            return "0";
        } else {
            return noSubsets;
        }
    }

    /**
     * Sets the value of the noSubsets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoSubsets(String value) {
        this.noSubsets = value;
    }

    /**
     * Gets the value of the fixedWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedWidth() {
        return fixedWidth;
    }

    /**
     * Sets the value of the fixedWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedWidth(String value) {
        this.fixedWidth = value;
    }

    /**
     * Gets the value of the fixedHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedHeight() {
        return fixedHeight;
    }

    /**
     * Sets the value of the fixedHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedHeight(String value) {
        this.fixedHeight = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the keywordList property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordList }
     *     
     */
    public KeywordList getKeywordList() {
        return keywordList;
    }

    /**
     * Sets the value of the keywordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordList }
     *     
     */
    public void setKeywordList(KeywordList value) {
        this.keywordList = value;
    }

    /**
     * Gets the value of the srs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the srs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SRS }
     * 
     * 
     */
    public List<SRS> getSRS() {
        if (srs == null) {
            srs = new ArrayList<SRS>();
        }
        return this.srs;
    }

    /**
     * Gets the value of the latLonBoundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link LatLonBoundingBox }
     *     
     */
    public LatLonBoundingBox getLatLonBoundingBox() {
        return latLonBoundingBox;
    }

    /**
     * Sets the value of the latLonBoundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link LatLonBoundingBox }
     *     
     */
    public void setLatLonBoundingBox(LatLonBoundingBox value) {
        this.latLonBoundingBox = value;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boundingBox property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoundingBox().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BoundingBox }
     * 
     * 
     */
    public List<BoundingBox> getBoundingBox() {
        if (boundingBox == null) {
            boundingBox = new ArrayList<BoundingBox>();
        }
        return this.boundingBox;
    }

    /**
     * Gets the value of the dimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dimension }
     * 
     * 
     */
    public List<Dimension> getDimension() {
        if (dimension == null) {
            dimension = new ArrayList<Dimension>();
        }
        return this.dimension;
    }

    /**
     * Gets the value of the extent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extent }
     * 
     * 
     */
    public List<Extent> getExtent() {
        if (extent == null) {
            extent = new ArrayList<Extent>();
        }
        return this.extent;
    }

    /**
     * Gets the value of the attribution property.
     * 
     * @return
     *     possible object is
     *     {@link Attribution }
     *     
     */
    public Attribution getAttribution() {
        return attribution;
    }

    /**
     * Sets the value of the attribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attribution }
     *     
     */
    public void setAttribution(Attribution value) {
        this.attribution = value;
    }

    /**
     * Gets the value of the authorityURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorityURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorityURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorityURL }
     * 
     * 
     */
    public List<AuthorityURL> getAuthorityURL() {
        if (authorityURL == null) {
            authorityURL = new ArrayList<AuthorityURL>();
        }
        return this.authorityURL;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the metadataURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataURL }
     * 
     * 
     */
    public List<MetadataURL> getMetadataURL() {
        if (metadataURL == null) {
            metadataURL = new ArrayList<MetadataURL>();
        }
        return this.metadataURL;
    }

    /**
     * Gets the value of the dataURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataURL }
     * 
     * 
     */
    public List<DataURL> getDataURL() {
        if (dataURL == null) {
            dataURL = new ArrayList<DataURL>();
        }
        return this.dataURL;
    }

    /**
     * Gets the value of the featureListURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureListURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureListURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureListURL }
     * 
     * 
     */
    public List<FeatureListURL> getFeatureListURL() {
        if (featureListURL == null) {
            featureListURL = new ArrayList<FeatureListURL>();
        }
        return this.featureListURL;
    }

    /**
     * Gets the value of the style property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the style property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStyle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Style }
     * 
     * 
     */
    public List<Style> getStyle() {
        if (style == null) {
            style = new ArrayList<Style>();
        }
        return this.style;
    }

    /**
     * Gets the value of the scaleHint property.
     * 
     * @return
     *     possible object is
     *     {@link ScaleHint }
     *     
     */
    public ScaleHint getScaleHint() {
        return scaleHint;
    }

    /**
     * Sets the value of the scaleHint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScaleHint }
     *     
     */
    public void setScaleHint(ScaleHint value) {
        this.scaleHint = value;
    }

    /**
     * Gets the value of the layer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Layer }
     * 
     * 
     */
    public List<Layer> getLayer() {
        if (layer == null) {
            layer = new ArrayList<Layer>();
        }
        return this.layer;
    }

}
