//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 10:00:55 PM EST 
//


package org.osmdroid.wms.v111;

//import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
//@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLegendGraphic }
     * 
     */
    public GetLegendGraphic createGetLegendGraphic() {
        return new GetLegendGraphic();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link DCPType }
     * 
     */
    public DCPType createDCPType() {
        return new DCPType();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link KeywordList }
     * 
     */
    public KeywordList createKeywordList() {
        return new KeywordList();
    }

    /**
     * Create an instance of {@link OnlineResource }
     * 
     */
    public OnlineResource createOnlineResource() {
        return new OnlineResource();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Attribution }
     * 
     */
    public Attribution createAttribution() {
        return new Attribution();
    }

    /**
     * Create an instance of {@link LogoURL }
     * 
     */
    public LogoURL createLogoURL() {
        return new LogoURL();
    }

    /**
     * Create an instance of {@link HTTP }
     * 
     */
    public HTTP createHTTP() {
        return new HTTP();
    }

    /**
     * Create an instance of {@link Get }
     * 
     */
    public Get createGet() {
        return new Get();
    }

    /**
     * Create an instance of {@link Post }
     * 
     */
    public Post createPost() {
        return new Post();
    }

    /**
     * Create an instance of {@link AuthorityURL }
     * 
     */
    public AuthorityURL createAuthorityURL() {
        return new AuthorityURL();
    }

    /**
     * Create an instance of {@link Style }
     * 
     */
    public Style createStyle() {
        return new Style();
    }

    /**
     * Create an instance of {@link LegendURL }
     * 
     */
    public LegendURL createLegendURL() {
        return new LegendURL();
    }

    /**
     * Create an instance of {@link StyleSheetURL }
     * 
     */
    public StyleSheetURL createStyleSheetURL() {
        return new StyleSheetURL();
    }

    /**
     * Create an instance of {@link StyleURL }
     * 
     */
    public StyleURL createStyleURL() {
        return new StyleURL();
    }

    /**
     * Create an instance of {@link ScaleHint }
     * 
     */
    public ScaleHint createScaleHint() {
        return new ScaleHint();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link ContactPersonPrimary }
     * 
     */
    public ContactPersonPrimary createContactPersonPrimary() {
        return new ContactPersonPrimary();
    }

    /**
     * Create an instance of {@link ContactAddress }
     * 
     */
    public ContactAddress createContactAddress() {
        return new ContactAddress();
    }

    /**
     * Create an instance of {@link PutStyles }
     * 
     */
    public PutStyles createPutStyles() {
        return new PutStyles();
    }

    /**
     * Create an instance of {@link DataURL }
     * 
     */
    public DataURL createDataURL() {
        return new DataURL();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link GetMap }
     * 
     */
    public GetMap createGetMap() {
        return new GetMap();
    }

    /**
     * Create an instance of {@link GetFeatureInfo }
     * 
     */
    public GetFeatureInfo createGetFeatureInfo() {
        return new GetFeatureInfo();
    }

    /**
     * Create an instance of {@link FeatureListURL }
     * 
     */
    public FeatureListURL createFeatureListURL() {
        return new FeatureListURL();
    }

    /**
     * Create an instance of {@link DescribeLayer }
     * 
     */
    public DescribeLayer createDescribeLayer() {
        return new DescribeLayer();
    }

    /**
     * Create an instance of {@link BoundingBox }
     * 
     */
    public BoundingBox createBoundingBox() {
        return new BoundingBox();
    }

    /**
     * Create an instance of {@link Capability }
     * 
     */
    public Capability createCapability() {
        return new Capability();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link VendorSpecificCapabilities }
     * 
     */
    public VendorSpecificCapabilities createVendorSpecificCapabilities() {
        return new VendorSpecificCapabilities();
    }

    /**
     * Create an instance of {@link UserDefinedSymbolization }
     * 
     */
    public UserDefinedSymbolization createUserDefinedSymbolization() {
        return new UserDefinedSymbolization();
    }

    /**
     * Create an instance of {@link Layer }
     * 
     */
    public Layer createLayer() {
        return new Layer();
    }

    /**
     * Create an instance of {@link LatLonBoundingBox }
     * 
     */
    public LatLonBoundingBox createLatLonBoundingBox() {
        return new LatLonBoundingBox();
    }

    /**
     * Create an instance of {@link GetCapabilities }
     * 
     */
    public GetCapabilities createGetCapabilities() {
        return new GetCapabilities();
    }

    /**
     * Create an instance of {@link GetStyles }
     * 
     */
    public GetStyles createGetStyles() {
        return new GetStyles();
    }

    /**
     * Create an instance of {@link WMTMSCapabilities }
     * 
     */
    public WMTMSCapabilities createWMTMSCapabilities() {
        return new WMTMSCapabilities();
    }

    /**
     * Create an instance of {@link SRS }
     * 
     */
    public SRS createSRS() {
        return new SRS();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link Extent }
     * 
     */
    public Extent createExtent() {
        return new Extent();
    }

    /**
     * Create an instance of {@link MetadataURL }
     * 
     */
    public MetadataURL createMetadataURL() {
        return new MetadataURL();
    }

}
