//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 01:27:59 PM EST 
//


package org.w3._1999.xlink;

import java.util.ArrayList;
import java.util.List;
/*import javax.xml.bind.annotation.XmlAccessType;*/
/*import javax.xml.bind.annotation.XmlAccessorType;*/
/*import javax.xml.bind.annotation.XmlAnyElement;*/
/*import javax.xml.bind.annotation.XmlAttribute;*/
/*import javax.xml.bind.annotation.XmlMixed;*/
/*import javax.xml.bind.annotation.XmlType;*/
import org.w3c.dom.Element;


/**
 * <p>Java class for titleEltType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="titleEltType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.w3.org/1999/xlink}titleModel"/>
 *       &lt;attGroup ref="{http://www.w3.org/1999/xlink}titleAttrs"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*@XmlAccessorType(XmlAccessType.FIELD)*/
/*@XmlType(name = "titleEltType", propOrder = {
    "content"
})*/
public class TitleEltType {

    /*@XmlMixed*/
    /*@XmlAnyElement(lax = true)*/
    protected List<Object> content;
    /*@XmlAttribute(name = "type", namespace = "http://www.w3.org/1999/xlink", required = true)*/
    protected TypeType type;
    /*@XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")*/
    protected String lang;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link String }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeType }
     *     
     */
    public TypeType getType() {
        if (type == null) {
            return TypeType.TITLE;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeType }
     *     
     */
    public void setType(TypeType value) {
        this.type = value;
    }

    /**
     * 
     *      xml:lang is not required, but provides much of the
     *      motivation for title elements in addition to attributes, and so
     *      is provided here for convenience.
     *     
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
