package org.osmdroid;

//this file is automatically generated during the build
//when making changes, only edit ./src/main/filtered/...
//https://github.com/osmdroid/osmdroid/issues/1500
public class OsmdroidBuildInfo {

    private OsmdroidBuildInfo() {
    }

    public static final String VERSION = "@pom.version@";
    public static final String BUILD_DATE = "@date@";
}