//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 01:27:59 PM EST 
//


package net.opengis.wms;

/*import javax.xml.bind.annotation.XmlAccessType;*/
/*import javax.xml.bind.annotation.XmlAccessorType;*/
/*import javax.xml.bind.annotation.XmlElement;*/
/*import javax.xml.bind.annotation.XmlRootElement;*/
/*import javax.xml.bind.annotation.XmlType;*/


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/wms}Title" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/wms}OnlineResource" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/wms}LogoURL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*@XmlAccessorType(XmlAccessType.FIELD)*/
/*@XmlType(name = "", propOrder = {
    "title",
    "onlineResource",
    "logoURL"
})*/
/*@XmlRootElement(name = "Attribution")*/
public class Attribution {

    /*@XmlElement(name = "Title")*/
    protected String title;
    /*@XmlElement(name = "OnlineResource")*/
    protected OnlineResource onlineResource;
    /*@XmlElement(name = "LogoURL")*/
    protected LogoURL logoURL;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the onlineResource property.
     * 
     * @return
     *     possible object is
     *     {@link OnlineResource }
     *     
     */
    public OnlineResource getOnlineResource() {
        return onlineResource;
    }

    /**
     * Sets the value of the onlineResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnlineResource }
     *     
     */
    public void setOnlineResource(OnlineResource value) {
        this.onlineResource = value;
    }

    /**
     * Gets the value of the logoURL property.
     * 
     * @return
     *     possible object is
     *     {@link LogoURL }
     *     
     */
    public LogoURL getLogoURL() {
        return logoURL;
    }

    /**
     * Sets the value of the logoURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogoURL }
     *     
     */
    public void setLogoURL(LogoURL value) {
        this.logoURL = value;
    }

}
