//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 01:27:59 PM EST 
//


package net.opengis.wms;

/*import javax.xml.bind.annotation.XmlAccessType;*/
/*import javax.xml.bind.annotation.XmlAccessorType;*/
/*import javax.xml.bind.annotation.XmlAttribute;*/
/*import javax.xml.bind.annotation.XmlElement;*/
/*import javax.xml.bind.annotation.XmlRootElement;*/
/*import javax.xml.bind.annotation.XmlSchemaType;*/
/*import javax.xml.bind.annotation.XmlType;*/
/*import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;*/
/*import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;*/


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/wms}OnlineResource"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*@XmlAccessorType(XmlAccessType.FIELD)*/
/*@XmlType(name = "", propOrder = {
    "onlineResource"
})*/
/*@XmlRootElement(name = "AuthorityURL")*/
public class AuthorityURL {

    /*@XmlElement(name = "OnlineResource", required = true)*/
    protected OnlineResource onlineResource;
    /*@XmlAttribute(name = "name", required = true)*/
    /*@XmlJavaTypeAdapter(CollapsedStringAdapter.class)*/
    /*@XmlSchemaType(name = "NMTOKEN")*/
    protected String name;

    /**
     * Gets the value of the onlineResource property.
     * 
     * @return
     *     possible object is
     *     {@link OnlineResource }
     *     
     */
    public OnlineResource getOnlineResource() {
        return onlineResource;
    }

    /**
     * Sets the value of the onlineResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnlineResource }
     *     
     */
    public void setOnlineResource(OnlineResource value) {
        this.onlineResource = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
