name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - temp/modernize
  pull_request:
    branches:
      - temp/modernize

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
